# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duplicateFinderUIui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 650)
        MainWindow.setMinimumSize(820,640)
        
        #Set Fixed Size
        #self.setFixedSize(1082,678)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, 0, 1081, 631))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_search = QtWidgets.QWidget()
        self.page_search.setObjectName("page_search")
        self.windowDirectory = QtWidgets.QTreeView(self.page_search)
        self.windowDirectory.setGeometry(QtCore.QRect(15, 40, 600, 590))
        self.windowDirectory.setObjectName("windowDirectory")
        self.windowDirectory.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.windowSelected = QtWidgets.QListView(self.page_search)
        self.windowSelected.setGeometry(QtCore.QRect(775, 40, 290, 590))
        self.windowSelected.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.windowSelected.setObjectName("windowSelected")
        self.windowSelected.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.buttonAdd = QtWidgets.QPushButton(self.page_search)
        self.buttonAdd.setGeometry(QtCore.QRect(630, 40, 131, 41))
        self.buttonAdd.setObjectName("buttonAdd")
        self.buttonRemove = QtWidgets.QPushButton(self.page_search)
        self.buttonRemove.setGeometry(QtCore.QRect(630, 92, 131, 41))
        self.buttonRemove.setObjectName("buttonRemove")
        self.buttonSearch = QtWidgets.QPushButton(self.page_search)
        self.buttonSearch.setGeometry(QtCore.QRect(630, 460, 131, 51))
        self.buttonSearch.setObjectName("buttonSearch")
        self.labelSearchOptions = QtWidgets.QLabel(self.page_search)
        self.labelSearchOptions.setGeometry(QtCore.QRect(650, 520, 91, 20))
        self.labelSearchOptions.setObjectName("labelSearchOptions")
        self.checkBoxFileName = QtWidgets.QCheckBox(self.page_search)
        self.checkBoxFileName.setGeometry(QtCore.QRect(630, 550, 121, 16))
        self.checkBoxFileName.setObjectName("checkBoxFileName")
        self.checkBoxFileSize = QtWidgets.QCheckBox(self.page_search)
        self.checkBoxFileSize.setGeometry(QtCore.QRect(630, 570, 121, 16))
        self.checkBoxFileSize.setObjectName("checkBoxFileSize")
        self.checkBoxHashSum = QtWidgets.QCheckBox(self.page_search)
        self.checkBoxHashSum.setGeometry(QtCore.QRect(630, 590, 121, 16))
        self.checkBoxHashSum.setObjectName("checkBoxHashSum")
        self.labelFolderSelection = QtWidgets.QLabel(self.page_search)
        self.labelFolderSelection.setGeometry(QtCore.QRect(20, 10, 131, 21))
        self.labelFolderSelection.setObjectName("labelFolderSelection")
        self.labelSelectedFolders = QtWidgets.QLabel(self.page_search)
        self.labelSelectedFolders.setGeometry(QtCore.QRect(780, 10, 131, 21))
        self.labelSelectedFolders.setObjectName("labelSelectedFolders")
        self.stackedWidget.addWidget(self.page_search)


        self.page_results = QtWidgets.QWidget()
        self.page_results.setObjectName("page_results")
        self.windowFoundDuplicates = QtWidgets.QListView(self.page_results)
        self.windowFoundDuplicates.setGeometry(QtCore.QRect(610, 40, 461, 591))
        self.windowFoundDuplicates.setAccessibleName("")
        self.windowFoundDuplicates.setAccessibleDescription("")
        self.windowFoundDuplicates.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.windowFoundDuplicates.setObjectName("windowFoundDuplicates")
        self.windowFoundDuplicates.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.windowFoundDuplicates.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.buttonDeleteSelected = QtWidgets.QPushButton(self.page_results)
        self.buttonDeleteSelected.setGeometry(QtCore.QRect(480, 120, 110, 41))
        self.buttonDeleteSelected.setObjectName("buttonDeleteSelected")
        self.buttonDeleteAll = QtWidgets.QPushButton(self.page_results)
        self.buttonDeleteAll.setGeometry(QtCore.QRect(480, 220, 110, 41))
        self.buttonDeleteAll.setObjectName("buttonDeleteAll")
        self.buttonClearEmpty = QtWidgets.QPushButton(self.page_results)
        self.buttonClearEmpty.setGeometry(QtCore.QRect(480, 300, 110, 41))
        self.buttonClearEmpty.setObjectName("buttonClearEmpty")
        self.checkBoxClearEmpty = QtWidgets.QCheckBox(self.page_results)
        self.checkBoxClearEmpty.setGeometry(QtCore.QRect(490, 350, 91, 31))
        self.checkBoxClearEmpty.setObjectName("checkBoxClearEmpty")
        self.buttonBack = QtWidgets.QPushButton(self.page_results)
        self.buttonBack.setGeometry(QtCore.QRect(480, 590, 110, 41))
        self.buttonBack.setObjectName("buttonBack")
        self.windowFoundPrimary = QtWidgets.QListView(self.page_results)
        self.windowFoundPrimary.setGeometry(QtCore.QRect(20, 40, 441, 591))
        self.windowFoundPrimary.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.windowFoundPrimary.setObjectName("windowFoundPrimary")
        self.windowFoundPrimary.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.windowFoundPrimary.setFrameShape(QtWidgets.QFrame.WinPanel)
        # self.windowFoundPrimary = QtWidgets.QColumnView(self.page_results)
        # self.windowFoundPrimary.setGeometry(QtCore.QRect(20, 40, 441, 591))
        # self.windowFoundPrimary.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        # self.windowFoundPrimary.setObjectName("windowFoundPrimary")
        self.buttonSwapOriginal = QtWidgets.QPushButton(self.page_results)
        self.buttonSwapOriginal.setGeometry(QtCore.QRect(480, 40, 110, 41))
        self.buttonSwapOriginal.setObjectName("buttonSwapOriginal")
        self.labelOriginal = QtWidgets.QLabel(self.page_results)
        self.labelOriginal.setGeometry(QtCore.QRect(20, 10, 131, 21))
        self.labelOriginal.setObjectName("labelOriginal")
        self.labelDuplicates = QtWidgets.QLabel(self.page_results)
        self.labelDuplicates.setGeometry(QtCore.QRect(610, 10, 131, 21))
        self.labelDuplicates.setObjectName("labelDuplicates")
        self.buttonDeleteDuplicates = QtWidgets.QPushButton(self.page_results)
        self.buttonDeleteDuplicates.setGeometry(QtCore.QRect(480, 170, 110, 41))
        self.buttonDeleteDuplicates.setObjectName("buttonDeleteDuplicates")
        self.buttonSaveCSV = QtWidgets.QPushButton(self.page_results)
        self.buttonSaveCSV.setGeometry(QtCore.QRect(480, 540, 110, 41))
        self.buttonSaveCSV.setObjectName("buttonSaveCSV")
        self.stackedWidget.addWidget(self.page_results)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.windowDirectory.setToolTip(_translate("MainWindow", "Select Folders to Add to Search"))
        self.windowSelected.setToolTip(_translate("MainWindow", "Folders Selected for Search"))
        self.buttonAdd.setToolTip(_translate("MainWindow", "Add Selected Folder to Search"))
        self.buttonAdd.setText(_translate("MainWindow", "ADD"))
        self.buttonRemove.setToolTip(_translate("MainWindow", "Remove Selected Folder from Search"))
        self.buttonRemove.setText(_translate("MainWindow", "REMOVE"))
        self.buttonSearch.setToolTip(_translate("MainWindow", "Initiate Search for Duplicate Files"))
        self.buttonSearch.setText(_translate("MainWindow", "SEARCH"))
        self.labelSearchOptions.setText(_translate("MainWindow", "Search Options"))
        self.checkBoxFileName.setToolTip(_translate("MainWindow", "Will match files based on file names"))
        self.checkBoxFileName.setText(_translate("MainWindow", "File Name"))
        self.checkBoxFileSize.setToolTip(_translate("MainWindow", "Will match files based on file size"))
        self.checkBoxFileSize.setText(_translate("MainWindow", "File Size"))
        self.checkBoxHashSum.setToolTip(_translate("MainWindow", "Will match files based on the contents of the file. Can be used without the File Name option if looking for duplicate files that have had their name changed."))
        self.checkBoxHashSum.setText(_translate("MainWindow", "Hash Sum"))
        self.labelFolderSelection.setText(_translate("MainWindow", "SELECT FOLDERS"))
        self.labelSelectedFolders.setText(_translate("MainWindow", "SELECTED FOLDERS"))
        self.windowFoundDuplicates.setToolTip(_translate("MainWindow", "Duplicate Files of Selected Original"))
        self.buttonDeleteSelected.setToolTip(_translate("MainWindow", "Delete Selected Duplicate File"))
        self.buttonDeleteSelected.setText(_translate("MainWindow", "DELETE SELECTED"))
        self.buttonDeleteAll.setToolTip(_translate("MainWindow", "Delete ALL Duplicates of ALL Original Files"))
        self.buttonDeleteAll.setText(_translate("MainWindow", "DELETE ALL"))
        self.buttonClearEmpty.setToolTip(_translate("MainWindow", "Clear All Original Files with no remaining Duplicates"))
        self.buttonClearEmpty.setText(_translate("MainWindow", "CLEAR EMPTY"))
        self.checkBoxClearEmpty.setToolTip(_translate("MainWindow", "Automatically clear Original Files with no remaining Duplicates"))
        self.checkBoxClearEmpty.setText(_translate("MainWindow", "Automatically\nClear Empty"))
        self.buttonBack.setToolTip(_translate("MainWindow", "Go Back to Folder Selection"))
        self.buttonBack.setText(_translate("MainWindow", "BACK"))
        self.windowFoundPrimary.setToolTip(_translate("MainWindow", "Files with Duplicates"))
        self.buttonSwapOriginal.setToolTip(_translate("MainWindow", "Change Selected Duplicate File to be the Original"))
        self.buttonSwapOriginal.setText(_translate("MainWindow", "SWAP ORIGINAL"))
        self.labelOriginal.setText(_translate("MainWindow", "ORIGINAL FILES"))
        self.labelDuplicates.setText(_translate("MainWindow", "DUPLICATE FILES"))
        self.buttonDeleteDuplicates.setToolTip(_translate("MainWindow", "Delete All Duplicates of Selected Original"))
        self.buttonDeleteDuplicates.setText(_translate("MainWindow", "DELETE DUPLICATES"))
        self.buttonSaveCSV.setToolTip(_translate("MainWindow", "Save .CSV of Deleted Files"))
        self.buttonSaveCSV.setText(_translate("MainWindow", "SAVE CSV FILE"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

